---
  - hosts: all
    vars_files: vars.yml
    become: true
    become_method: sudo
        
    tasks:
      - name: Change root password
        ansible.builtin.user:
          name: root
          password: "{{ userpwd | password_hash('sha512') }}"
