---
  - hosts: all
    vars_files: vars.yml
    become: true
    become_method: sudo
        
    tasks:
      - name: Shell command - Register vm with RH subscription
        ansible.builtin.command: "{{ registration }}"

          
          
